name: greetings

# Controls when the workflow will run
on:
    workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
